### ISSUE TITLE
Make  Fibonacci Chicken

### ISSUE THREAD

**Issue by SejuneOh** [jusunjo/pizz#3]
#피보나치 치킨  js 파일 만들기 

## Tasks 

- [ ] Make Fibonacci.js 
- [ ] Add  Fibonacci  Numbers  Function 
- [ ] Add Fibonacci  Chicken Function
